# Generated by Django 5.1 on 2024-08-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
